### PR TITLE
System includes

### PR DESCRIPTION
**Pull request by calid**
Add tcc system include dirs and common Unix system include dirs by default

### CODE REVIEW

**Comment by plicease** [comment]
We can do this, but it isn't quite as easy as adding `/usr/include`.  On Debian and Ubuntu Linux of recent vintage they have arch specific include directories, for amd64 it is `/usr/include/x86_64-linux-gnu/`.  I suspect that explains the travis error.  I suspect that some of the header files will expect certain defines to be made as well.

I had a similar issue with `PkgConfig.pm` and this is how I handled it:

https://github.com/mnunberg/perl-PkgConfig/commit/c7b20c928428405514fc38f917166411c42bc5f2

Good news is that the set of platforms where `FFI::TinyCC` has to work is much smaller than `PkgConfig.pm` so it is probably doable.

**Comment by calid** [comment]
No I don't think that alone will work as I originally tried that, but it complained about gnu specific defines on my Arch Linux box, so something more is needed.  Also, rather than hardcoding the includes I think it's better to get this dynamically on Unix from `cpp -v`

`C::TinyCompiler` doesn't have this problem, so I wonder what it's doing differently?  For example this works without issue for me:

```perl
use Test::More;
use C::TinyCompiler;

my $c = C::TinyCompiler->new('C::TinyCompiler::Callable');
$c->code('Body') =<< "END";
    #include <errno.h>
    #include <stddef.h>

    C::TinyCompiler::Callable
    int ohhai(void) { return 42; }
END

$c->compile();
ok 42 == $c->get_callable_subref('ohhai')->();
```

**Comment by plicease** [comment]
Problem with `cpp` is that it isn't always available.  Though it *might* be available on platforms that are supported by TinyCC.

**Comment by plicease** [comment]
I wasn't able to install `C::TinyCompiler`.

**Comment by plicease** [comment]
Actually looks like $Config{incpath} may have what we are looking for:

```
incpth=/usr/local/include /home/ollisg/opt/clang/3.5/bin/../lib/clang/3.5.0/include /usr/include/x86_64-linux-gnu /usr/include
```

**Comment by calid** [comment]
> I wasn't able to install C::TinyCompiler.

This is what originally motivated me to switch to `FFI::TinyCC` :).  If you install from the git repo it will work, the version on cpan has busted test comparisons on newer Perls.

> Actually looks like $Config{incpath} may have what we are looking for

For me it was `$Config{incpth}`, looks like you need to try both:

```
$ perl -MConfig -E 'say $Config{incpath}'

$ perl -MConfig -E 'say $Config{incpth}'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include /usr/local/include /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include-fixed /usr/include
```

**Comment by calid** [comment]
@plicease I take it back, I added the paths from `$Config` and it's working for me locally, so maybe something else was going on.  I've updated the patch.

**Comment by plicease** [comment]
`incpath` was a typo on my part.  It doesn't seem to be universally available, so I will have to do some checking here and there.  Looks like `C::TinyCompiler` uses `locincpth` which yields the wrong results for me in most places.

**Comment by plicease** [comment]
Looks like `incpth` was introduced in Perl 5.20.  Looking at the Configure script that comes with Perl 5.20, I don't think it would be too hard to reverse engineer it into Perl.  We can calculate the value ourselves for older Perls and use $Config{incpth} for newer Perls.

The only problem is that it appears to work only with gcc and clang.  I'd like to support non-gcc/clang compilers if possible.

**Comment by calid** [comment]
> The only problem is that it appears to work only with gcc and clang. I'd like to support non-gcc/clang compilers if possible.

I guess I don't understand, isn't `tcc` the only compiler being targeted by this module?

**Comment by calid** [comment]
The man page for `tcc` on both Arch Linux and Debian says:

> The default system include paths are: /usr/local/include, /usr/include and PREFIX/lib/tcc/include. (PREFIX is usually /usr or /usr/local).

So it seems odd to me we would have to add the arch specific dirs where tcc itself does not...

**Comment by plicease** [comment]
The header files in `/usr/include` refer to the arch specific header files.  For example `<stdio.h>` is in `/usr/include`, but it refers to `<bits/types.h>`, which on my Debian Linux lives in `/usr/include/x86_64-linux-gnu/bits/types.h`.  The work around employed by `C::TinyCompiler` is to add `/usr/include/i386-linux-gnu` to the include path, which is wrong on AMD64 machines like mine, or really anything that isn't 32bit intel.

I just double checked and the `tcc` command finds `<bits/types.h>` although it is not in `/usr/include`.  I suspect that the Debian folk have patched `tcc` itself, but not the man page for it.  In my experience this is not uncommon.

Now we can get the appropriate include paths either from `$Config{incpth}` if it is available (Perl 5.20, and only if it was built with gcc or clang), or directly from the compiler used to build Perl itself.  I suggested using the same method as Perl does, which is implemented inside the shell script Configure that comes with the Perl source code.

I'd like to support this capability, and I think it is doable, but I want to do it as correctly as possible.

**Comment by calid** [comment]
Ok, that makes sense now.  Thanks for the explanation.

**Comment by plicease** [comment]
I got this working using a combination the .h files that come with tinycc and the directories in the `incpth`.  I want to do some more "weird platform testing" just to be sure my assumptions are sound.  Hopefully can get a production version on CPAN later this week.

**Comment by plicease** [comment]
`0.17_01` adds a `detect_sysinclude_path` method that attempts to detect the correct sysinclude path for you.  It throws an exception if the platform is not supported.  I expect it to work with any platform where you are using clang or gcc including windows.  If it doesn't explode on cpantesters then I will cut a production release in a day or two.

**Comment by calid** [comment]
@plicease this passes for me locally, but curious why [line 15](https://github.com/plicease/FFI-TinyCC/blob/193fdb3b35dba5ccd973459893c8f700faf8ff98/t/detect_sysinclude_path.t#L15) in detect_sysinclude_path.t is necessary?  Isn't the idea users shouldn't have to explicitly add any system includes?

**Comment by plicease** [comment]
That was my bad it shouldn't be there at all.

**Comment by plicease** [comment]
0.18 is on its way to CPAN.

**Comment by calid** [comment]
@plicease just installed the new version and was surprised when my script still failed.  Looking more closely it seems `detect_sysinclude_path` needs to be manually called by the user.  Any reason not to make this the default?

If not the default should probably at least add it to the SYNOPSIS.. although I think default would be nice so things Just Work™ :)

**Comment by calid** [comment]
also having it return a list of the detected sysinclude path would probably be useful.

**Comment by plicease** [comment]
@calid It isn't the default because `FFI::TinyCC` is an API to libtcc, and `detect_sysinclude_path` is a convenience function for determining the appropriate include paths.  For me `FFI::TinyCC` has utility in some cases without the system header files and I don't want to make detecting them accurately a hard requirement.  If a dependency needs that it can verify that `detect_sysinclude_path` does not throw an exception in the config step.

I'll add an example to the SYNOPSIS as you suggest and `detect_sysinclude_path` can return the paths that it detects, that is reasonable.

**Comment by calid** [comment]
ok, no problem.  thanks!

**Comment by plicease** [comment]
Thanks for the suggestions :) I've updated and released 0.19

**Pull request closed without merging**
